### ISSUE TITLE
Tutorial5

### ISSUE THREAD

**Issue by YuviAndBeyond** [krittikaiitb/tutorials#39]
Messier3.fits file missing from tutorial_5 folder, please can you reupload it

**Comment by Curovearth** [comment]
@YuviAndBeyond Found this [site](https://www.jimmynewland.com/wp/astro/messier-3-project/) with the `.fits` file present. Can @krittikaIITB confirm if we can use this for the tutorial since there are 5 data files for each of the U, G, R, I, and Z filters used by SDSS telescopes are present.

**_Edit 1:_** 
I am using G Filter .fits data. There's a limitation to the data here but I feel that won't be of a big trouble. The only problem I encountered was I am unable to plot the Messier Object.

My **m3_data** looks like this 

```
[[1055 1057 1059 ... 1059 1062 1061]
 [1051 1059 1051 ... 1059 1056 1064]
 [1049 1061 1056 ... 1059 1059 1054]
 ...
 [1059 1060 1059 ... 1088 1075 1058]
 [1060 1059 1054 ... 1112 1086 1057]
 [1055 1055 1052 ... 1131 1090 1050]]
```
After writing the code below, I am not able to get the plot (The code runs but doesn't display anything)
```
plt.figure(figsize=(6,6))
plt.imshow(m3_data)
plt.show()
```

Am I going wrong somewhere ?

**_Edit2:_** 

If someone is facing the same trouble. @Bhavesh012 pointed out the culprit in my code i.e.,  `%matplotlib notebook` . Avoid using this and use instead `%matplotlib inline`

**Comment by Bhavesh012** [comment]
> @YuviAndBeyond Found this [site](https://www.jimmynewland.com/wp/astro/messier-3-project/) with the `.fits` file present. Can @krittikaIITB confirm if we can use this for the tutorial since there are 5 data files for each of the U, G, R, I, and Z filters used by SDSS telescopes are present.
> 
> **_Edit 1:_** 
> I am using G Filter .fits data. There's a limitation to the data here but I feel that won't be of a big trouble. The only problem I encountered was I am unable to plot the Messier Object.
> 
> My **m3_data** looks like this 
> 
> ```
> [[1055 1057 1059 ... 1059 1062 1061]
>  [1051 1059 1051 ... 1059 1056 1064]
>  [1049 1061 1056 ... 1059 1059 1054]
>  ...
>  [1059 1060 1059 ... 1088 1075 1058]
>  [1060 1059 1054 ... 1112 1086 1057]
>  [1055 1055 1052 ... 1131 1090 1050]]
> ```
> After writing the code below, I am not able to get the plot (The code runs but doesn't display anything)
> ```
> plt.figure(figsize=(6,6))
> plt.imshow(m3_data)
> plt.show()
> ```
> 
> Am I going wrong somewhere ?

Hey,
What happens exactly after the cell runs? Does a blank figure appear does nothing happen at all?

**Comment by Curovearth** [comment]
> > @YuviAndBeyond Found this [site](https://www.jimmynewland.com/wp/astro/messier-3-project/) with the `.fits` file present. Can @krittikaiitb confirm if we can use this for the tutorial since there are 5 data files for each of the U, G, R, I, and Z filters used by SDSS telescopes are present.
> > **_Edit 1:_**
> > I am using G Filter .fits data. There's a limitation to the data here but I feel that won't be of a big trouble. The only problem I encountered was I am unable to plot the Messier Object.
> > My **m3_data** looks like this
> > ```
> > [[1055 1057 1059 ... 1059 1062 1061]
> >  [1051 1059 1051 ... 1059 1056 1064]
> >  [1049 1061 1056 ... 1059 1059 1054]
> >  ...
> >  [1059 1060 1059 ... 1088 1075 1058]
> >  [1060 1059 1054 ... 1112 1086 1057]
> >  [1055 1055 1052 ... 1131 1090 1050]]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After writing the code below, I am not able to get the plot (The code runs but doesn't display anything)
> > ```
> > plt.figure(figsize=(6,6))
> > plt.imshow(m3_data)
> > plt.show()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Am I going wrong somewhere ?
> 
> Hey, What happens exactly after the cell runs? Does a blank figure appear does nothing happen at all?

I don't see any figure, It's completely blank and no errors as such

**Comment by DEVANSH-DVJ** [comment]
Uploaded the missing fits file.
Thanks for pointing it out.
